apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: angular-app
        imagePullPolicy: Never
        env:
          - name: DOTNET_API_URL
            # Using the nginx reverse proxy on the angular app to proxy_pass to the backend
            # In production, this would be the actual backend URL that uses an ingress route
            value: "/api"
          - name: HOST_TYPE
            value: "k8s"
          - name: PROD
            value: "true"
# 🔧 Create a second Deployment for the webapi
# 💡 Copy paste is your friend ;)
