apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: webapi
spec:
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: dotnet-api
        imagePullPolicy: Never
        livenessProbe:
        # 🔧 Fix the issue with the liveness probe when you are at step 4
        # 💡 Sometimes two characters are enough to kill your application...
          httpGet:
            path: /unhealthy
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3