apiVersion: v1
kind: ConfigMap
metadata:
  name: webapi-logging-config
data:
  Logging__LogLevel__Default: "Trace"
---
# 🔧 Uncomment the manifest below when you are at step 5
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: webapi
#   labels:
#     app: webapi
# spec:
#   selector:
#     matchLabels:
#       app: webapi
#   template:
#     metadata:
#       labels:
#         app: webapi
#     spec:
#       containers:
#       - name: webapi
#         image: dotnet-api
#         imagePullPolicy: Never
#         livenessProbe:
#           httpGet:
#             path: /healthy
#             port: 80
#           initialDelaySeconds: 3
#           periodSeconds: 3
#         envFrom:
#           - configMapRef:
#               name: webapi-logging-config
