apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  Logging_LogLevel_Default: "Trace"
---
# 🔧 Uncomment the manifest below when you are at step 3
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: webapp
#   labels:
#     app: webapp
# spec:
#   selector:
#     matchLabels:
#       app: webapp
#   template:
#     metadata:
#       labels:
#         app: webapp
#     spec:
#       containers:
#       - name: webapp
#         image: angular-app
#         imagePullPolicy: Never
#         envFrom:
#           - configMapRef:
#               name: webapp-config
