apiVersion: v1
kind: ConfigMap
metadata:
  name: webapi-apioptions-config
data:
  appsettings.override.json: |-
    {
      "ApiOptions": {
        "Message": "Hello from the ConfigMap ;)"
      }
    }
---
# 🔧 Uncomment the manifest below when you are at step 3
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: webapi
#   labels:
#     app: webapi
# spec:
#   selector:
#     matchLabels:
#       app: webapi
#   template:
#     metadata:
#       labels:
#         app: webapi
#     spec:
#       containers:
#       - name: webapi
#         image: dotnet-api
#         imagePullPolicy: Never
#         livenessProbe:
#           httpGet:
#             path: /healthy
#             port: 80
#           initialDelaySeconds: 3
#           periodSeconds: 3
#         envFrom:
#           - configMapRef:
#               name: webapi-logging-config
#         volumeMounts:
#           - name: webapi-apioptions-config-volume
#             mountPath: /app/config
#             readOnly: true
#       volumes:
#         - name: webapi-apioptions-config-volume
#           configMap:
#             name: webapi-apioptions-config